# Generated by Django 4.1.2 on 2023-01-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhruthi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(default='heading', max_length=25)),
                ('Image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
